### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by ghost** [clarknoah/ise-jingu-feedback#12]
**Describe the bug**
![image](https://user-images.githubusercontent.com/41160280/73849253-9de8df00-47f7-11ea-9774-8a68643d159e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clarknoah** [comment]
Thanks Mark!
