### ISSUE TITLE
Response Issue - Applying DOM Queries

### ISSUE THREAD

**Issue by caioingber** [clarknoah/ise-jingu-feedback#15]
**Describe the bug**

**To Reproduce**
The question below says to utilize the query method that pulls the first occurance of a node element that matches that search, however, the required answer says to utilize querySelectorAll. This is in the Applying DOM Queries lesson.

<img width="1418" alt="Screen Shot 2020-02-06 at 09 08 00" src="https://user-images.githubusercontent.com/57416150/73944457-9c371e00-48c0-11ea-9a95-895c04bfb86c.png">

**Comment by clarknoah** [comment]
Fixed, thanks!
