### ISSUE TITLE
Submit bug

### ISSUE THREAD

**Issue by digitalfences** [clarknoah/ise-jingu-feedback#19]
**Describe the bug**
submit button lags, appearing to be broken until the profile is successfully created
**To Reproduce**
1. Go to homepage
2. Click on sign up
3. fill information in and click submit
4. the button presses and does not seem to work

**Expected behavior**
The prompt should disappear and show some type of processing message before the profile is created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Mac newest OS
 - Browser [e.g. chrome, safari]Brave Browser

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clarknoah** [comment]
This bug has been fixed, thanks a bunch!
