### ISSUE TITLE
Opening Links

### ISSUE THREAD

**Issue by ghost** [clarknoah/ise-jingu-feedback#2]
**Describe the bug**
When I clicked the Instagram icon it opened the link on my current page. I hit the backspace and it made me start all over again. Suggest opening new links in a new tab.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clarknoah** [comment]
I'll get this fixed in a jiffy! Thank you!

**Comment by clarknoah** [comment]
Once again, thank you for catching this, the issue has been closed and resolved!
