### ISSUE TITLE
putting the flex items to bed

### ISSUE THREAD

**Issue by colleenobrien3** [clarknoah/ise-jingu-feedback#4]
<img width="913" alt="Screen Shot 2020-01-24 at 9 06 18 AM" src="https://user-images.githubusercontent.com/59711779/73075081-2034e300-3e89-11ea-918c-9208fe3cf983.png">

Idk if this image will show up, but there's just a typo in one of the learn definitions, unless putting the flex items to bed is a concept I have not yet learned, which really wouldn't surprise me that much.

In the CSS Flex Declarations learn. the answer is justify-content: space around, i think it's like the third one. Idk if you even care about typos or if this forum is just for like bugs, but I just thought I'd let you know

**Comment by clarknoah** [comment]
Wow thanks a ton for catching this typo! Issue has been closed!
