### ISSUE TITLE
Typo for Answer to CSS Display Property lesson

### ISSUE THREAD

**Issue by caioingber** [clarknoah/ise-jingu-feedback#5]
Less of a bug, more of a typo which does not recognize the correct spelling as the answer:

Under the lesson: CSS - Display Property

The following question shows the correct answer as "diplay" instead of "display" once moving to the answering portion it was not recognizing "display" as a valid answer. See attached screenshot for reference.

This error appears to apply to all modes of the lesson (i.e. learn, practice & test).
<img width="1327" alt="Screen Shot 2020-01-24 at 10 05 24" src="https://user-images.githubusercontent.com/57416150/73078893-2dee6680-3e91-11ea-9f79-e18d186e5fef.png">

**Comment by clarknoah** [comment]
Thanks a TON Caio, really appreciate the feedback! Issue has been resolved!
