### ISSUE TITLE
Slight issue 

### ISSUE THREAD

**Issue by andrew-frazier6** [clarknoah/ise-jingu-feedback#6]
**Describe the bug**
As I was answer the JS Data question about boolean, I accidently typed aen as opposed to ean and when i hit backspace it counted the question as an attempt and missed question. Not sure if its really a bug or inconvenience. Maybe the script written could be a little more "forgiving" for lack of a better term. I apologize if that comes across as picky, but I had just noticed it a few other times in other questions but this one stood out to me 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - chrome
 - Version: most up to date 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by clarknoah** [comment]
Thanks for the feedback, working on a feature right now to meet your usecase!
